extends: default

rules:
  # Prettier (printWidth: 120) と競合するため無効化
  line-length: disable

  # Prettier がスタイルを制御するため無効化
  braces: disable
  brackets: disable
  colons: disable
  commas: disable

  # インデントは Prettier の tabWidth: 2 と一致させる
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  # truthy ルールは実用的に設定
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
    check-keys: false

  # コメントインデントは無効化
  comments-indentation: disable

  # YAML構文として重要なルールは有効
  key-duplicates: enable
  trailing-spaces: enable
